---
- name: Install prerequisite packages for Grafana
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - software-properties-common

- name: Add Graphana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Graphana APT repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    update_cache: yes

- name: Install Graphana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Set Grafana admin password
  command: grafana-cli --homepath "/usr/share/grafana" admin reset-admin-password {{ graphite_web_password }}

- name: Fix permission/owner for /var/lib/grafana
  file:
    dest: /var/lib/grafana
    owner: grafana
    group: grafana
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  notify:
    - restart grafana

- name: Enable grafana-service
  service:
    name: grafana-server
    enabled: yes
  notify:
    - restart grafana
