Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.network :private_network, ip: '192.168.49.49'

  config.vm.provider :virtualbox do |vb|
      vb.memory = 2048
      vb.linked_clone = true
  end


  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  #
  # Then run Ansible from the Vagrant Host
  #
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.raw_arguments = [ '--diff' ]

    ansible.playbook = "playbook.yml"
    ansible.sudo_user = 'root'
    ansible.sudo = true

    ansible.groups = {
      'frontend'   => [ 'default' ],
      'vagrant'    => [ 'default' ],    #
    }

    if ENV['ANSIBLE_TAGS'] then ansible.tags = ENV['ANSIBLE_TAGS']; end

  end

  if File.exist?(".vagrant/machines/default/virtualbox/action_provision")
  	#
  	# Already provisioned, it's now safe to use "config.vm.synced_folder" statements
  	# and additional scripts that require the users exist
    
    # Edit line below to get shared folder sync
    config.vm.synced_folder "../../poster/src/", "/opt/poster-app/src", id: "source-root",
        owner: "poster-app",
        group: "poster-app",
        mount_options: ["dmode=775,fmode=664"]
  	#
  else
  	#
  	# Not yet provisioned, only run the script that creates the required users
  	#
  end



end
