- name: Install python pip
  apt:
    name:
      - python-pip
      - python3-pip
      - python-virtualenv
    state: present

- name: Setup virtualenv as in uwsgi apps
  include: one-app.yml
  with_items: '{{ uwsgi_apps }}'
  loop_control:
    loop_var: _uwsgi_app
