nginx_ppa_use: false
nginx_client_max_body_size: "64m"
nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "80 default"
    server_name: "example.net"
    root: "/var/www/html"
    index: "index.html"
    access_log: "/var/log/nginx/access_log"
    error_log: "/var/log/nginx/access_log"
    state: "present"
#    template: "{{ nginx_vhost_template }}"
    filename: "example.net.conf"
#    extra_parameters: |
#      location ~ \.php$ {
#          fastcgi_split_path_info ^(.+\.php)(/.+)$;
#          fastcgi_pass unix:/var/run/php5-fpm.sock;
#          fastcgi_index index.php;
#          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#          include fastcgi_params;
#      }
#      ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
#      ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
#      ssl_protocols       TLSv1.1 TLSv1.2;
#      ssl_ciphers         HIGH:!aNULL:!MD5;