---
- set_fact:
    _uwsgi_virtualenv: '{{ _uwsgi_app.app_root }}/virtualenv'
    _uwsgi_activate: '{{ _uwsgi_app.app_root }}/virtualenv/bin/activate'

- name: "Compile requirements"
  shell: '{{ _uwsgi_virtualenv }}/bin/pip install -r {{ _uwsgi_app.app_root }}/src/requirements.txt'
  args:
    chdir: '{{ _uwsgi_app.app_root }}'
  become_user: '{{ _uwsgi_app.user }}'

- name: "Create custom local_settings <{{ _uwsgi_app.name }}>"
  template:
    src: local_settings.j2
    dest: '{{ _uwsgi_app.src_root }}/poster/local_settings.py'
    owner: poster-app

- name: Add virtualenv to login script
  become_user: '{{ _uwsgi_app.user }}'
  lineinfile:
    dest: '{{ _uwsgi_app.app_root }}/uwsgi.ini'
    line: "python-autoreload = 1"
    state: present

- name: "Django manage"
  shell: '{{ _uwsgi_virtualenv }}/bin/python manage.py migrate; {{ _uwsgi_virtualenv }}/bin/python manage.py collectstatic --noinput'
  args:
    chdir: '{{ _uwsgi_app.src_root }}'
  become_user: '{{ _uwsgi_app.user }}'
  # ignore_errors: yes

- name: Remove wsgi entrypoint
  file:
    state: absent
    path: "{{ _uwsgi_app.app_root }}/src/wsgi.py"
  ignore_errors: yes

- name: Link wsgi entrypoint
  file:
    src: "{{ _uwsgi_app.app_root }}/src/poster/wsgi.py"
    dest: "{{ _uwsgi_app.app_root }}/src/wsgi.py"
    state: link
    force: yes

- name: "Create version.py for reload"
  file:
    path: "{{ _uwsgi_app.app_root }}/version.py"
    state: touch
    owner: "{{ _uwsgi_app.user }}"
    group: "{{ _uwsgi_app.user }}"
