---
- name: Configure basic HTTP
  ufw:
    rule: allow
    port: http
    proto: tcp
  notify:
    - restart ufw

- name: Configure basic HTTPS
  ufw:
    rule: allow
    port: https
    proto: tcp
  notify:
    - restart ufw
