---
- name: "Compile requirements"
  shell: '{{ _uwsgi_virtualenv }}/bin/pip install -r /opt/poster-app/src/requirements.txt'
  args:
    chdir: '{{ _uwsgi_app.app_root }}'
  become_user: '{{ _uwsgi_app.user }}'

- name: "Create custom local_settings <{{ _uwsgi_app.name }}>"
  template:
    src: local_settings.j2
    dest: '{{ _uwsgi_app.src_root }}/poster/local_settings.py'
    owner: poster-app
