---
- set_fact:
    _uwsgi_virtualenv: '{{ _uwsgi_app.app_root }}/virtualenv'
    _uwsgi_activate: '{{ _uwsgi_app.app_root }}/virtualenv/bin/activate'

- name: "Compile requirements"
  shell: '{{ _uwsgi_virtualenv }}/bin/pip install -r {{ _uwsgi_app.app_root }}/src/requirements.txt'
  args:
    chdir: '{{ _uwsgi_app.app_root }}'
  become_user: '{{ _uwsgi_app.user }}'

- name: "Create custom local_settings <{{ _uwsgi_app.name }}>"
  template:
    src: local_settings.j2
    dest: '{{ _uwsgi_app.src_root }}/poster/local_settings.py'
    owner: poster-app

- name: "RE-Start celery as service"
  systemd: state=started enabled=yes name='celery-{{ _uwsgi_app.name }}.service' daemon_reload=yes
